language: clojure
lein: 2.7.1
script:
  - lein deps
  - lein compile
  - lein uberjar
  - lein test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
notifications:
  email:
      - bjorn@billo.systems
